apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
  template:
    metadata:
      labels:
        app: aceest-fitness
    spec:
      containers:
        - name: aceest-fitness-container
          image: aceest-fitness-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000