apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-blue-green
  labels:
    app: aceest-fitness
spec:
  selector:
    app: aceest-fitness
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
