apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-shadow
  labels:
    app: aceest-fitness
    version: shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
      version: shadow
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: shadow
    spec:
      containers:
        - name: aceest-fitness
          image: ghcr.io/roshanjson/aceest-fitness-and-gym:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_NAME
              value: "/data/aceest_fitness.db"
            - name: SHADOW_MODE
              value: "true"
          readinessProbe:
            httpGet:
              path: /clients
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /clients
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20